name: Frontend

on: push

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format, Lint and Organize Imports
        run: bun run biome:write

      - name: Check if all issues are fixed
        run: bun run biome:ci

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "refactor(GHActionbot): :art: formatted & linting & organized imports with biome" || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: biome
          delete-branch: true
          title: "Biome changes"

      - name: Test with Jest
        run: bun run test

      - name: Build
        run: bun run build

  e2e:
    name: "E2E"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: E2E with Playwright
        env:
          CI: true
        run: bun e2e

      - name: Upload playwright Acticats
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
